# repo config
repo_name: 'bentarnoff/docs-mysql'
repo_url: 'https://github.com/bentarnoff/docs-mysql'
edit_uri: edit/master/docs/
site_name: MySQL for PCF 
theme: 'material'

# left nav
pages:
  - MySQL for PCF:
    - 'Home': 'index.md'
    - 'Release Notes': 'release-notes.md'
    - 'Architecture': 'architecture.md'
    - 'Known Issues': 'known-issues.md'
  - Operator Guide:
    - 'Installing MySQL for PCF': 'installing.md'
    - 'Configuring MySQL for PCF': 'configuring.md'
    - 'Service Plans': 'service-plan.md'
    - 'MySQL Proxy': 'proxy.md'
    - 'Backups': 'backup.md'
    - 'Application Security Groups': 'app-security-groups.md'
    - 'Monitoring': 'monitoring-mysql.md'
    - 'Troubleshooting': 'troubleshooting.md'
    - 'Bootstrapping': 'bootstrapping.md'
    - 'Rotating Credentials': 'credential-rotation.md'
    - 'Running mysql-diag': 'mysql-diag.md'
  - Application Developer Guide:
    - 'Getting Started': 'getting-started.md'
    - 'When/How to RSU': 'rsu.md'


# palette, logo, css, markdown extensions
extra:
  palette:
    primary: 'teal'
    accent: 'deep orange'
  logo: 'images/common/pivotal-logo.png'
  feature:
    tabs: true
extra_css:
    - 'css/highlight-fix.css'
    - 'css/solarized_dark.css'
    - 'css/extras.css'
    # - 'css/all.css'
    # - 'css/print.css'
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(linenums=true)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde